// DO NOT MODIFY THIS FILE.
// This entire file was automatically generated by ModAssemblyInfo.csproj.
// Make any needed changes in ModAssemblyInfo.csproj.

namespace RadiusDelete
{
    /// <summary>
    /// Make assembly info available as constant strings.
    /// </summary>
    public class ModAssemblyInfo
    {
        public const string Name        = "RadiusDelete";
        public const string Version     = "1.0";
        public const string Title       = "Radius Delete: Bulk Bulldoze";
        public const string Description = "A radius bulldoze tool that supports object type filters.";
    }
}
